apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for VOD demo"
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
