apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic-system
    server: https://kubernetes.default.svc
  project: calfolguera
  source:
    path: .
    repoURL: https://github.com/hfolguera/kubernetes-elasticsearch.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/1/clientConfig/caBundle
      - /webhooks/2/clientConfig/caBundle
      - /webhooks/3/clientConfig/caBundle
      - /webhooks/4/clientConfig/caBundle
      - /webhooks/5/clientConfig/caBundle
      - /webhooks/6/clientConfig/caBundle
      - /webhooks/7/clientConfig/caBundle
      - /webhooks/8/clientConfig/caBundle
      - /webhooks/9/clientConfig/caBundle
      - /webhooks/10/clientConfig/caBundle
      - /webhooks/11/clientConfig/caBundle
      - /webhooks/12/clientConfig/caBundle
