apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microbin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: microbin
    server: https://kubernetes.default.svc
  project: calfolguera
  source:
    path: .
    repoURL: https://github.com/hfolguera/kubernetes-microbin.git
    targetRevision: HEAD
  syncPolicy: {}