apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle23ai
  namespace: argocd
spec:
  destination:
    namespace: oracle
    server: https://kubernetes.default.svc
  project: calfolguera
  source:
    path: .
    repoURL: https://github.com/hfolguera/kubernetes-oracle23ai.git
    targetRevision: HEAD
  syncPolicy: {}