apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: calfolguera
  source:
    path: .
    repoURL: https://github.com/hfolguera/kubernetes-postgres.git
    targetRevision: HEAD
  syncPolicy: {}