apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shinobi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: shinobi
    server: https://kubernetes.default.svc
  project: calfolguera
  source:
    path: .
    repoURL: https://github.com/hfolguera/kubernetes-shinobi.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
