apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vod-video-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vod
    server: https://kubernetes.default.svc
  project: vod
  source:
    path: kubernetes
    repoURL: https://github.com/hfolguera/vod-video-service.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
